project_id: '554895'
base_path: i18n
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /i18n/en_US.csv
  - source: /i18n/pt_BR.csv
targets:
  - name: /i18n/pt_BR.csv
    sources:
      - /i18n/en_US.csv
    file: /i18n/%locale_with_underscore%.csv
    format: crowdin-csv
  - name: /i18n/es_AR.csv
    sources:
      - /i18n/en_US.csv
    file: /i18n/%locale_with_underscore%.csv
    format: crowdin-csv
  - name: /i18n/es_CL.csv
    sources:
      - /i18n/en_US.csv
    file: /i18n/%locale_with_underscore%.csv
    format: crowdin-csv
  - name: /i18n/es_CO.csv
    sources:
      - /i18n/en_US.csv
    file: /i18n/%locale_with_underscore%.csv
    format: crowdin-csv
  - name: /i18n/es_MX.csv
    sources:
      - /i18n/en_US.csv
    file: /i18n/%locale_with_underscore%.csv
    format: crowdin-csv
  - name: /i18n/es_MX.csv
    sources:
      - /i18n/en_PE.csv
    file: /i18n/%locale_with_underscore%.csv
    format: crowdin-csv
