name: Validate Versions

on: [pull_request]

jobs:
  validate-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer
      
      - name: Verify PHP Installation
        run: php -v

      - name: Validate Composer
        run: composer validate

      - name: Validate Version
        run: bash bin/validate-version.sh


      
